meta_product_name: "Somnium"
meta_title: "Somnium - Bring your dreams to consciousness"
meta_description: "Somnium app allows you to keep a writen record of your dreams, categorize them and track your dreams through time."
meta_image: "somnium.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards